export const FETCHING_POSTS = 'FETCHING_POSTS';
export const FETCHING_POSTS_REJECTED = 'FETCHING_POSTS_REJECTED';
export const FETCHING_POSTS_FULFILLED = 'FETCHING_POSTS_FULFILLED';

export const FETCHING_USERS = 'FETCHING_USERS';
export const FETCHING_USERS_REJECTED = 'FETCHING_USERS_REJECTED';
export const FETCHING_USERS_FULFILLED = 'FETCHING_USERS_FULFILLED';

export const FETCHING_ALBUMS = 'FETCHING_ALBUMS';
export const FETCHING_ALBUMS_REJECTED = 'FETCHING_ALBUMS_REJECTED';
export const FETCHING_ALBUMS_FULFILLED = 'FETCHING_ALBUMS_FULFILLED';


